version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
  
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.1
    ports:
      - "5601:5601"
