#!/bin/bash
#
# Source any '.sh' scripts in /docker-entrypoint-initdb.d.

set -e

# execute files in /docker-entrypoint-initdb.d before starting any test
while read f; do
    case "$f" in
        *.sh)     echo "$0: running $f"; . "$f" ;;
        *)        echo "$0: ignoring $f" ;;
    esac
    echo
done < <(find /docker-entrypoint-initdb.d/ -mindepth 1 -type f | sort -n)
